### ISSUE TITLE
uchování vybraných hesel u záznamu

### ISSUE THREAD

**Issue by OgDInstant** [techlib/toc#1]
bug, nefunguje nám uchování vybraných hesel u záznamu (není žádné tlačítko uložit, ani se neuchovají vybrané hodnoty po překliknutí na jiný záznam)

**Comment by albertoh** [comment]
Pridal jsem tlacitko "SAVE" 
Ten uklada do slovniku "nerizene" vsechna vybrana hesla ze sloupce "bez slovniku"

**Comment by albertoh** [comment]
Opraveno podle mailu.
Ted pri kliknuti na SAVE, ulozime soubor do konfiguracniho adresare / tocs. 
Pri kliknuti na sysno, app se pokusi cist z adresare ulozenych nejdrive.
Jako test jsem ulozil 000004104 a 000005010
Staci je zmazat z adresare, aby se neukazaly jako ulozene, nebo vybrat spravna hesla a ulozit znovu

**Comment by OgDInstant** [comment]
Otestování (kromě mazání), funkční
