### ISSUE TITLE
Ruční přidání klíčového slova

### ISSUE THREAD

**Issue by OgDInstant** [techlib/toc#3]
Pokud se nenachází v navržených PSH, klíčových slovech, volných termínech ten pravý, přidat možnost ručního přidání klíčového slova.

**Comment by albertoh** [comment]
Pridal jsem tlacitko "ADD"
Otevre dialog, kde je mozne pridavat nova hesla. Nasledne tlacitkem "SAVE" ulozime vsechna vybrana a pridana nova hesla do slovniku "nerizene"

**Comment by OgDInstant** [comment]
Otestováno, funkční.
