### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by OgDInstant** [techlib/toc#8]
Po weekendové odstávce serverů v NTK nenaběhl správně TOC prosím o nápravu, případě informaci jak postupovat. Děkuji

**Comment by albertoh** [comment]
Nastartovano.
Meli bychom tam delat startovaci skrypty.
Ted jsem startoval rucne tomcat a solr

**Comment by OgDInstant** [comment]
Děkuji,

to by určitě chtělo, přeci jen výpadky serverů nejsou neobvyklé. Udělám na to issue.
